-- MySQL Script generated by MySQL Workbench
-- 12/15/16 14:00:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `AnswerID` INT(11) NOT NULL AUTO_INCREMENT,
  `Answer_Text` TEXT NOT NULL,
  `Positive_Score` INT(11) NULL DEFAULT '0',
  `Negative_Score` INT(11) NULL DEFAULT '0',
  `time` TIMESTAMP NULL DEFAULT NULL,
  `Score` INT(11) GENERATED ALWAYS AS ((`Positive_Score` - `Negative_Score`)) VIRTUAL,
  PRIMARY KEY (`AnswerID`),
  UNIQUE INDEX `idAnswers_UNIQUE` (`AnswerID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 78
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`),
  UNIQUE INDEX `CategoryID_UNIQUE` (`CategoryID` ASC),
  UNIQUE INDEX `Category_Name_UNIQUE` (`Category_Name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `QuestionID` INT(11) NOT NULL AUTO_INCREMENT,
  `Question_text` TEXT NOT NULL,
  `timeposted` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`QuestionID`),
  UNIQUE INDEX `idQuestions_UNIQUE` (`QuestionID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Has_Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Has_Answer` (
  `QuestionID` INT(11) NOT NULL,
  `AnswerID` INT(11) NOT NULL,
  CONSTRAINT `Answer_ID`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `mydb`.`Answer` (`AnswerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Question_ID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Question` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Has_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Has_Category` (
  `CategoryID` INT(11) NOT NULL,
  `QuestionID` INT(11) NOT NULL,
  CONSTRAINT `Category__ID`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `mydb`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Question__ID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Question` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Posted_Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posted_Answer` (
  `UserID` INT(11) NOT NULL,
  `AnswerID` INT(11) NOT NULL,
  CONSTRAINT `Answer__ID`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `mydb`.`Answer` (`AnswerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `User__ID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Posted_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posted_Question` (
  `UserID` INT(11) NOT NULL,
  `QuestionID` INT(11) NOT NULL,
  CONSTRAINT `Question____ID`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `mydb`.`Question` (`QuestionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `User____ID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
